#!/bin/sh

if track="`echo $(git symbolic-ref --short -q HEAD) | sed 's/track\///g'| sed 's/scratch\///g' | sed 's/\/.*//g'`"
then
  echo "Executing: git pull origin track/$track"
  git pull origin track/$track
else
  echo ERROR: must specify track
fi
