#!/bin/sh

if [ -z "$1" ]
then
	echo 'ERROR: Did not pass name as an agrument'
	echo 'Usage: git newscratchbranch <name>'
else
	if currentBranch=$(git symbolic-ref --short -q HEAD)
	then
	  track="`git track`"
	  trackName="`echo $track | sed -e 's/track\///g'`"
	  echo On track $track
	  newbranch="scratch/$trackName/$1"
	  echo Creating new branch $newbranch
	  git branch -m $newbranch
	else
	  echo ERROR: Cannot find the current branch!
	fi
fi