#!/bin/sh
GITHUB_URL="`git remote get-url origin |sed -e "s/.git$//g"`"

if currentBranch=$(git symbolic-ref --short -q HEAD)
then
  track="`git track`"
  echo On track $track
  echo On branch $currentBranch
  open "$GITHUB_URL/compare/$track...$currentBranch"
else
  echo ERROR: Cannot find the current branch!
fi
