#!/bin/sh

# Find which is your current branch
if currentBranch=$(git symbolic-ref --short -q HEAD)
then
  echo On branch $currentBranch
  echo "Reseting current branch $currentBranch with the origin"
  git reset --hard origin/$currentBranch
else
  echo ERROR: Cannot find the current branch!
fi
